### PR TITLE
Shortening shell prompt.

### PR DESCRIPTION
**Pull request by widdowquinn**
I found that working in directories that were quite deep in the directory tree gave very long shell prompts which made recorded sessions difficult to read and follow.

Changing the PS1 shell prompt from \w to \W only puts the current directory in the shell prompt, improving legibility.

It might be nice to make this an option at the command-line; my approach here is a bit heavy-handed.

### CODE REVIEW

**Comment by mboisson** [comment]
Indeed, it would be best to have an option when invoking the script. I personnally like to have the whole path for completeness.

**Comment by widdowquinn** [comment]
I do see your point, and prefer to see the full shell when I am working in the shell by myself. For teaching though, I think there are two other considerations:
1. The shell being used is often being projected, so the text on-screen might need to be a much larger font size than on the monitor if it's to be seen clearly - especially if it's SVGA, in a large room! The full path might be distractingly long.
2. Long paths interfere with HTML presentation of the recorded text, as can be seen here: [http://kkwakwa.github.io/2015-11-16-manchester-codima/codima_lessons/make/runthrough_shell.html](http://kkwakwa.github.io/2015-11-16-manchester-codima/codima_lessons/make/runthrough_shell.html)

Those problems go away with a single-directory prompt: [http://kkwakwa.github.io/2015-11-16-manchester-codima/codima_lessons/make/2015-11-16-make-lesson.html](http://kkwakwa.github.io/2015-11-16-manchester-codima/codima_lessons/make/2015-11-16-make-lesson.html)

**Comment by mboisson** [comment]
Hi,
I have integrated the changes in a bigger commit, which allows this as an option when calling the script. 
The script now has some proper parsing of command line argument as well. 

The commit is this one : 
https://github.com/mboisson/recording-script/commit/309627ce5679e2a332971b3fadb7edfbe8dbe790

I will close this pull request.

Maxime

**Comment by beroe** [comment]
I have s she'll function that records commands to a text file )'(like on Dropbox) and I found it was helpful to add #REC> to the prompt to remind myself to stop recording at some point.

**Comment by mboisson** [comment]
If you simply "exit" the session you are in, it will stop the recording. Since the prompt that is being used is already different than a default prompt, I don't see this as a problem.

Please open a new pull request if you want to contribute a flag to add something like this.

**Pull request closed without merging**
